function NetworkGui(handles)

     fh = figure('units','pixels',...
              'units','normalized',...
              'position',[0.25 0.25 .175 .125],...
              'menubar','none',...
              'name','Select Graph Clustering Method',...
              'tag','networkgui',...
              'numbertitle','off',...
              'resize','off');
    guidata(fh,handles);


    clusteroptions=uicontrol('Style','listbox',...
    'String',{'Modularity Max - Louvain';'Modularity Max - Fast Greedy';'Modularity Max - Newman';...
    'Danon Method';'Spectral Clustering'},...
    'units','normalized',...
    'Position',[.1,.3,0.8,0.6],...
    'Tag','graphclusteropt');

    selectbutton=uicontrol('Style','pushbutton',...
        'String','Select',...
        'units','normalized',...
        'Position',[0.75,.1,.2,0.2],...
        'Tag','selectgraphcluster',...
        'Callback',@selectgraphcluster);
end

    function selectgraphcluster(hObject, eventdata)
        temp=findobj('Tag','graphclusteropt');
        clustergraphmethod=temp.Value;
        handles=guidata(hObject);
        handles.graphclustermethod=clustergraphmethod;
        guidata(findobj('Tag','Cluster'),handles);
        closereq;

    end
